# Tensorflow2.0 小练习

In [115]:
import tensorflow as tf
import numpy as np

## 实现softmax函数

In [116]:
def softmax(x):
    ##########
    '''实现softmax函数，只要求对最后一维归一化，
    不允许用tf自带的softmax函数'''
    ##########
    prob_x = np.exp(x) / np.sum(np.exp(x), axis=1, keepdims=True)
#     prob_x = tf.exp(x) / tf.reduce_sum(tf.exp(x), axis=-1)
    return prob_x

test_data = np.random.normal(size=[10, 5])
# softmax(test_data).numpy() == tf.nn.softmax(test_data, axis=-1).numpy()
(softmax(test_data) - tf.nn.softmax(test_data, axis=-1).numpy())**2<0.0001

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

## 实现sigmoid函数

In [117]:
def sigmoid(x):
    ##########
    '''实现sigmoid函数， 不允许用tf自带的sigmoid函数'''
    ##########
    prob_x = 1 / (1 + np.exp(-x))
#     prob_x = 1 / (1 + tf.exp(-x))
    return prob_x

test_data = np.random.normal(size=[10, 5])
(sigmoid(test_data) - tf.nn.sigmoid(test_data).numpy())**2 < 0.0001

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

## 实现 softmax 交叉熵loss函数

In [118]:
def softmax_ce(x, label):
    ##########
    '''实现 softmax 交叉熵loss函数， 不允许用tf自带的softmax_cross_entropy函数'''
    ##########
    loss = - np.sum(np.log(softmax(x))* label) / len(x)
#     loss = - tf.reduce_sum(label * tf.math.log(tf.nn.softmax(x))) / len(x)
    return loss

test_data = np.random.normal(size=[10, 5])
label = np.zeros_like(test_data)
label[np.arange(10), np.random.randint(0, 5, size=10)]=1.

((tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits(label, test_data))
  - softmax_ce(test_data, label))**2 < 0.0001).numpy()

True

## 实现 sigmoid 交叉熵loss函数

In [119]:
def sigmoid_ce(x, label):
    ##########
    '''实现 sigmoid 交叉熵loss函数， 不允许用tf自带的sigmoid_cross_entropy函数'''
    ##########
    loss= - np.sum(label * np.log(sigmoid(x)) + (1 - label) * np.log(1 - sigmoid(x))) / len(x)
#     loss = np.sum(- x * label + np.log(1 + np.exp(x))) / len(x)
    return loss

test_data = np.random.normal(size=[10])
label = np.random.randint(0, 2, 10).astype(test_data.dtype)
print (label)


((tf.reduce_mean(tf.nn.sigmoid_cross_entropy_with_logits(label, test_data))- sigmoid_ce(test_data, label))**2 < 0.0001).numpy()


[1. 0. 1. 1. 1. 0. 1. 1. 1. 0.]


True